baseURL = "https://sjakthol.github.io/"
languageCode = "en-us"
title = "Sami Jaktholm"

[params]
    author = "Sami Jaktholm"
    description = "Data Engineer at F-Secure. Student at Aalto University"
    accent = "blue"
    backgroundColor = "white"
    font = "Quicksand"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 2

[[menu.icon]]
    url = "mailto:sjakthol@outlook.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/sjakthol/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/sjakthol"
    name = "linkedin"
    weight = 3
